### PR TITLE
Fix line numbers in source maps and stack traces

### LINKED ISSUE #259: Stack traces display incorrect line numbers
**Description of the bug**
If an error is thrown in a Vue SFC, the line number of the statement that threw the error is incorrect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create SFC in .vue file
2. Throw an error in the `<script>` part of the SFC and don't handle it
3. View the stack trace in the error screen on the device/simulator or in the debugging tools

**What I expected**
The line number should match the line number in the user's source code

**Code sample**
```
<script>
export default {
  data() {
    return {
      message: 'Hello',
    };
  },
  methods: {
    p() {
      this.message += '!';
    },
  },
  mounted() {
    function t() {
      throw new Error('Mock error'); // line 15
    }
    t(); // line 17
    console.log(10 < 20);
  },
};
</script>

<template>
  <view class="container">
    <text class="text-color-primary">My Vue Native App</text>
    <text class="text-color-primary">{{ message }}</text>
    <button title="Press" @press="p" />
  </view>
</template>

<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.text-color-primary {
  color: blue;
}
</style>
```

**Screenshots**

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes, although it also occurs on bare RN based projects

**Development platform:**
- OSX Catalina 10.15.4
- ZSH

**The device on which I run my Vue Native app**
 - Device: any iPhone or Android device
 - OS: all supported variants

### PR DESCRIPTION
**Pull request by rahul-mahato**
Fix #259

### CODE REVIEW

File: src/platforms/vue-native/scripts/compiler.js [hunk 1]
```diff
@@ -243,8 +265,33 @@ function traverse(ast, nodes = []) {
...
+    if (line.includes('export')) {
+      lineOfExport = index
+      return true
+    } else {
+      return false
+    }
+  })
+  return lineOfExport
+}
+function getLineOfRVOptions(content) {
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:286]: Lines should be left between functions
```suggestion

function getLineOfReactVueOptions(content) {
```

File: src/platforms/vue-native/scripts/compiler.js [hunk 2]
```diff
@@ -243,8 +265,33 @@ function traverse(ast, nodes = []) {
...
+    ast.childNodes.forEach((child) => {
       traverse(child, nodes)
     })
   }
 }
+
+function getLineOfExport(content) {
+  var lineOfExport = 0
+  content.split(newLine).some((line, index) => {
+    if (line.includes('export')) {
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:277]: This may also match the string `export`, if it is inside a string and not being used as a keyword. Could we check this in a better way?

File: src/platforms/vue-native/scripts/compiler.js [hunk 3]
```diff
@@ -51,117 +50,137 @@ export function compileVueToRn(resource) {
...
-    //
-    var beforeLines = output.split(splitRE).length
     // Start of the script content of the original code
     //
-    var scriptLine =
-      code.slice(0, cparsed.script.start).split(splitRE).length + 1
-    var exportDefaultIndex = code.indexOf('export default')
-    var tempString = code.substring(0, exportDefaultIndex)
-    var exportDefaultLineNumber = tempString.split('\n').length
+    var scriptTagLineNumber = getLineOfExport(parsedSFC.script.content)
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:110]: What if there is code outside the `export` block, after the imports?

File: src/platforms/vue-native/scripts/compiler.js [hunk 4]
```diff
@@ -248,3 +271,46 @@ function traverse(ast, nodes = []) {
...
+      firstLine = index
+      return true
+    } else {
+      return false
+    }
+  })
+  return firstLine
+}
+
+function getFirstNonLineOfText(content, text) {
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:292]:
```suggestion
function getFirstLineWithoutText(content, text) {
```

File: src/platforms/vue-native/scripts/compiler.js [hunk 5]
```diff
@@ -248,3 +271,46 @@ function traverse(ast, nodes = []) {
     })
   }
 }
+
+function getFirstLineOfText(content, text) {
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:275]:
```suggestion
function getFirstLineWithText(content, text) {
```

File: src/platforms/vue-native/scripts/compiler.js [hunk 6]
```diff
@@ -248,3 +271,46 @@ function traverse(ast, nodes = []) {
...
+  var firstLine = 0
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:276]:
```suggestion
  let firstLine = 0
```

File: src/platforms/vue-native/scripts/compiler.js [hunk 7]
```diff
@@ -248,3 +271,46 @@ function traverse(ast, nodes = []) {
...
+  let splittedContent = content.split(newLine)
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:277]:
```suggestion
  let contentByLine = content.split(newLine)
```

File: src/platforms/vue-native/scripts/compiler.js [hunk 8]
```diff
@@ -248,3 +271,46 @@ function traverse(ast, nodes = []) {
...
+  if (!content.includes(text)) {
+    return splittedContent.length
+  }
+  splittedContent.some((line, index) => {
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:281]: Code is confusing. `some` should be used to check for membership in an array.

Would be better to use [findIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex)

Would also remove the need for the additional variable `firstLine`

File: src/platforms/vue-native/scripts/compiler.js [hunk 9]
```diff
@@ -248,3 +271,46 @@ function traverse(ast, nodes = []) {
...
+      return true
+    } else {
+      return false
+    }
+  })
+  return firstLine
+}
+
+function getFirstNonLineOfText(content, text) {
+  var firstNonCommentedLine = 0
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:293]:
```suggestion
  let firstNonCommentedLine = 0
```

Use `const` for declarations and `let` only if there is a need to mutate. Avoid `var`

File: src/platforms/vue-native/scripts/compiler.js [hunk 10]
```diff
@@ -248,3 +271,46 @@ function traverse(ast, nodes = []) {
...
+  let splittedContent = content.split(newLine)
+
+  if (!content.includes(text)) {
+    return 0
+  }
+  splittedContent.some((line, index) => {
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/compiler.js:299]: Code is confusing. `some` should be used to check for membership in an array.

Would be better to use [findIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex)

Would also remove the need for the additional variable `firstNonCommentedLine`

File: src/platforms/vue-native/scripts/transformerPlugin.js [hunk 11]
```diff
@@ -29,22 +29,23 @@ if (reactNativeMinorVersion >= 59) {
...
-          node.loc.end.line = originalEnd.line
-          node.loc.end.column = originalEnd.column
-        }
+function sourceMapAstInPlace(sourceMap, babelAst) {
+  const consumer = new SourceMapConsumer(sourceMap)
+
+  traverse.cheap(babelAst, node => {
+    if (node.loc) {
+      const originalStart = consumer.originalPositionFor(node.loc.start)
+      // Removed the column mapping with original position as we have only mapped lines during generation
```
Comment (RishabhKarnad) [inline src/platforms/vue-native/scripts/transformerPlugin.js:38]: @rahul-mahato We should leave the column mapping as it is unless it is causing issues.

You can add your thoughts in this thread

**Review by RishabhKarnad — CHANGES_REQUESTED** [review]

**Review by RishabhKarnad — APPROVED** [review]
